### ISSUE TITLE
[안드로이드] 피부타입 자가진단 리스트 기능 구현

### ISSUE THREAD

**Issue by rhksrb99** [2021-SMHRD-KDT-IoT-1/cos_table#10]
피부타입 자가진단 리스트 기능 구현

- [x] 질문에 대한 응답에 따른 피부타입 결과 도출 기능

**Comment by woyeonggwang** [comment]
텍스트뷰 클릭하여 체크리스트 액티비티로 이동하는 기능 구현완료
